# Generated by Django 2.0.6 on 2019-03-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='directions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='ingredients',
            field=models.TextField(default=''),
        ),
    ]
