# Generated by Django 2.0.6 on 2019-03-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_auto_20190311_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='image',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
